import type { Config } from "tailwindcss";
import { colours, spacing, fontSizes, fontWeights, letterSpacing, lineHeights, borderRadius, shadows } from "@seatly/tokens";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: colours.primary,
        "primary-hover": colours.primaryHover,
        secondary: colours.secondary,
        "secondary-hover": colours.secondaryHover,
        background: colours.background,
        surface: colours.surface,
        "surface-muted": colours.surfaceMuted,
        text: colours.text,
        "text-muted": colours.textMuted,
        border: colours.border,
        "border-muted": colours.borderMuted,
        success: colours.success,
        "success-muted": colours.successMuted,
        warning: colours.warning,
        "warning-muted": colours.warningMuted,
        error: colours.error,
        "error-muted": colours.errorMuted,
        info: colours.info,
        "info-muted": colours.infoMuted,
        "table-empty": colours.tableEmpty,
        "table-arriving": colours.tableArriving,
        "table-seated": colours.tableSeated,
        "table-overdue": colours.tableOverdue,
        "table-reserved": colours.tableReserved,
        "floor-plan-empty": colours.floorPlanEmpty,
        "floor-plan-empty-border": colours.floorPlanEmptyBorder,
        "floor-plan-seated": colours.floorPlanSeated,
        "floor-plan-seated-border": colours.floorPlanSeatedBorder,
        "floor-plan-arriving": colours.floorPlanArriving,
        "floor-plan-arriving-border": colours.floorPlanArrivingBorder,
        "floor-plan-overdue": colours.floorPlanOverdue,
        "floor-plan-overdue-border": colours.floorPlanOverdueBorder,
        "floor-plan-reserved": colours.floorPlanReserved,
        "floor-plan-reserved-border": colours.floorPlanReservedBorder,
        "background-dark": colours.backgroundDark,
        "surface-dark-alt": colours.surfaceDarkAlt,
        "surface-dark": colours.surfaceDark,
        "surface-dark-elevated": colours.surfaceDarkElevated,
        "border-dark": colours.borderDark,
        "text-on-dark": colours.textOnDark,
        "text-muted-on-dark": colours.textMutedOnDark,
        gold: colours.gold,
        "gold-muted": colours.goldMuted,
        "gold-dark": colours.goldDark,
        "gold-glow": colours.goldGlow,
        "gold-border-focus": colours.goldBorderFocus,
        "text-on-gold": colours.textOnGold,
        "border-card": colours.borderCard,
      },
      spacing: {
        xs: spacing.xs,
        sm: spacing.sm,
        md: spacing.md,
        lg: spacing.lg,
        xl: spacing.xl,
        "2xl": spacing["2xl"],
        "3xl": spacing["3xl"],
        "4xl": spacing["4xl"],
      },
      fontSize: {
        xs: fontSizes.xs,
        sm: fontSizes.sm,
        base: fontSizes.base,
        lg: fontSizes.lg,
        xl: fontSizes.xl,
        "2xl": fontSizes["2xl"],
        "3xl": fontSizes["3xl"],
        "4xl": fontSizes["4xl"],
      },
      fontWeight: {
        normal: fontWeights.normal,
        medium: fontWeights.medium,
        semibold: fontWeights.semibold,
        bold: fontWeights.bold,
        extrabold: fontWeights.extrabold,
      },
      letterSpacing: {
        "tight-hero": letterSpacing.tightHero,
        "tight-section": letterSpacing.tightSection,
        label: letterSpacing.label,
      },
      lineHeight: {
        relaxed: lineHeights.relaxed,
      },
      borderRadius: {
        sm: borderRadius.sm,
        md: borderRadius.md,
        lg: borderRadius.lg,
        xl: borderRadius.xl,
        full: borderRadius.full,
      },
      boxShadow: {
        sm: shadows.sm,
        md: shadows.md,
        lg: shadows.lg,
        "gold-glow": colours.goldGlow,
        "gold-glow-hover": colours.goldGlowHover,
        "gold-glow-hero-text": colours.goldGlowHeroText,
        "gold-glow-pricing-card": colours.goldGlowPricingCard,
        "inset-card": colours.insetShadowCard,
      },
      textShadow: {
        "gold-glow-hero": colours.goldGlowHeroText,
      },
      backgroundImage: {
        "gold-gradient-hero": colours.goldGradientHero,
        "gold-gradient-card-top": colours.goldGradientCardTop,
        "gold-gradient-text": colours.goldGradientText,
        "gold-gradient-text-muted": colours.goldGradientTextMuted,
        "gold-glow-section": colours.goldGlowSection,
        "radial-gradient-dark-center": colours.radialGradientDarkCenter,
        "gold-border-gradient": colours.goldBorderGradient,
        "grid-pattern": `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100' height='100'%3E%3Cdefs%3E%3Cpattern id='d' width='24' height='24' patternUnits='userSpaceOnUse'%3E%3Ccircle cx='12' cy='12' r='0.5' fill='white'/%3E%3C/pattern%3E%3C/defs%3E%3Crect width='100' height='100' fill='url(%23d)'/%3E%3C/svg%3E")`,
      },
      backgroundColor: {
        "gold-tint": colours.goldTintBg,
        "surface-glass": colours.surfaceGlass,
      },
      keyframes: {
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "200% 0" },
          "100%": { backgroundPosition: "-200% 0" },
        },
        gradientBorder: {
          "0%, 100%": { opacity: "0.5" },
          "50%": { opacity: "1" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        waveform: {
          "0%, 100%": { transform: "scaleY(0.3)" },
          "50%": { transform: "scaleY(1)" },
        },
      },
      animation: {
        "fade-in-up": "fadeInUp 0.6s ease-out forwards",
        shimmer: "shimmer 2s ease-in-out",
        "gradient-border": "gradientBorder 2s ease-in-out infinite",
        pulse: "pulse 2s ease-in-out infinite",
        waveform: "waveform 1.2s ease-in-out infinite",
      },
      transitionDuration: {
        "400": "400ms",
        "600": "600ms",
      },
    },
  },
  plugins: [],
};

export default config;
