import type { Config } from "tailwindcss";
import { colours, spacing, fontSizes, fontWeights, letterSpacing, lineHeights, borderRadius, shadows } from "@seatly/tokens";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: colours.primary,
        "primary-hover": colours.primaryHover,
        secondary: colours.secondary,
        "secondary-hover": colours.secondaryHover,
        background: colours.background,
        surface: colours.surface,
        "surface-muted": colours.surfaceMuted,
        text: colours.text,
        "text-muted": colours.textMuted,
        border: colours.border,
        "border-muted": colours.borderMuted,
        success: colours.success,
        "success-muted": colours.successMuted,
        warning: colours.warning,
        "warning-muted": colours.warningMuted,
        error: colours.error,
        "error-muted": colours.errorMuted,
        info: colours.info,
        "info-muted": colours.infoMuted,
        "table-empty": colours.tableEmpty,
        "table-arriving": colours.tableArriving,
        "table-seated": colours.tableSeated,
        "table-overdue": colours.tableOverdue,
        "table-reserved": colours.tableReserved,
        "floor-plan-empty": colours.floorPlanEmpty,
        "floor-plan-empty-border": colours.floorPlanEmptyBorder,
        "floor-plan-seated": colours.floorPlanSeated,
        "floor-plan-seated-border": colours.floorPlanSeatedBorder,
        "floor-plan-arriving": colours.floorPlanArriving,
        "floor-plan-arriving-border": colours.floorPlanArrivingBorder,
        "floor-plan-overdue": colours.floorPlanOverdue,
        "floor-plan-overdue-border": colours.floorPlanOverdueBorder,
        "floor-plan-reserved": colours.floorPlanReserved,
        "floor-plan-reserved-border": colours.floorPlanReservedBorder,
        "background-dark": colours.backgroundDark,
        "surface-dark-alt": colours.surfaceDarkAlt,
        "surface-dark": colours.surfaceDark,
        "surface-dark-elevated": colours.surfaceDarkElevated,
        "border-dark": colours.borderDark,
        "text-on-dark": colours.textOnDark,
        "text-muted-on-dark": colours.textMutedOnDark,
        gold: colours.gold,
        "gold-muted": colours.goldMuted,
        "gold-dark": colours.goldDark,
        "text-muted-gold": colours.textMutedGold,
        "gold-glow": colours.goldGlow,
        "gold-border-focus": colours.goldBorderFocus,
        "text-on-gold": colours.textOnGold,
        "border-card": colours.borderCard,
        "header-date-muted": colours.headerDateMuted,
        "status-arriving-bg": colours.statusArrivingBg,
        "status-arriving-text": colours.statusArrivingText,
        "status-confirmed-bg": colours.statusConfirmedBg,
        "status-confirmed-text": colours.statusConfirmedText,
        "status-seated-bg": colours.statusSeatedBg,
        "status-seated-text": colours.statusSeatedText,
        "status-overdue-bg": colours.statusOverdueBg,
        "status-overdue-text": colours.statusOverdueText,
        "briefing-text": colours.briefingText,
        "table-row-text": colours.tableRowText,
        "floor-plan-canvas-bg": colours.floorPlanCanvasBg,
        "floor-plan-canvas-dot": colours.floorPlanCanvasDot,
        "floor-plan-save-success": colours.floorPlanSaveSuccess,
        "floor-plan-save-pending": colours.floorPlanSavePending,
        "floor-plan-wall-border": colours.floorPlanWallBorder,
        "floor-plan-panel-bg": colours.floorPlanPanelBg,
        "floor-plan-panel-border": colours.floorPlanPanelBorder,
        "floor-plan-icon-muted": colours.floorPlanIconMuted,
        "floor-plan-icon-hover": colours.floorPlanIconHover,
        "floor-plan-section-label": colours.floorPlanSectionLabelColor,
        "floor-plan-inactive-border": colours.floorPlanInactiveBorder,
        "floor-plan-inactive-text": colours.floorPlanInactiveText,
        "floor-plan-inactive-hover-border": colours.floorPlanInactiveHoverBorder,
        "floor-plan-add-level-text": colours.floorPlanAddLevelText,
        "floor-plan-add-level-hover": colours.floorPlanAddLevelHover,
        "floor-plan-section-divider": colours.floorPlanSectionDivider,
        "floor-plan-card-bg": colours.floorPlanCardBg,
        "floor-plan-card-border": colours.floorPlanCardBorder,
        "floor-plan-card-hover-border": colours.floorPlanCardHoverBorder,
        "floor-plan-card-hover-bg": colours.floorPlanCardHoverBg,
        "floor-plan-circle-border": colours.floorPlanCircleBorder,
        "floor-plan-card-label": colours.floorPlanCardLabel,
        "floor-plan-pill-border": colours.floorPlanPillBorder,
        "floor-plan-pill-hover-border": colours.floorPlanPillHoverBorder,
        "floor-plan-pill-hover-text": colours.floorPlanPillHoverText,
        "floor-plan-wall-pill-border": colours.floorPlanWallPillBorder,
        "floor-plan-wall-pill-text": colours.floorPlanWallPillText,
        "floor-plan-walls-placed-text": colours.floorPlanWallsPlacedText,
        "floor-plan-empty-icon": colours.floorPlanEmptyIconColor,
        "floor-plan-empty-text": colours.floorPlanEmptyTextColor,
        "floor-plan-selected-card-bg": colours.floorPlanSelectedCardBg,
        "floor-plan-selected-card-border": colours.floorPlanSelectedCardBorder,
        "floor-plan-field-label": colours.floorPlanFieldLabel,
        "floor-plan-input-bg": colours.floorPlanInputBg,
        "floor-plan-input-border": colours.floorPlanInputBorder,
        "floor-plan-delete-bg": colours.floorPlanDeleteBg,
        "floor-plan-delete-border": colours.floorPlanDeleteBorder,
        "floor-plan-delete-text": colours.floorPlanDeleteText,
        "floor-plan-delete-hover-bg": colours.floorPlanDeleteHoverBg,
      },
      maxWidth: {
        "content-max": colours.contentMaxWidth,
      },
      spacing: {
        xs: spacing.xs,
        sm: spacing.sm,
        md: spacing.md,
        lg: spacing.lg,
        xl: spacing.xl,
        "2xl": spacing["2xl"],
        "3xl": spacing["3xl"],
        "4xl": spacing["4xl"],
        "stat-card": spacing.statCardPadding,
        "page-padding": spacing.pagePadding,
        "section-gap": spacing.sectionGap,
        "stat-card-gap": spacing.statCardGap,
        "section-margin": spacing.sectionMargin,
        "top-nav-height": spacing.topNavHeight,
        "sidebar-width": spacing.sidebarWidth,
        "sidebar-expanded-width": spacing.sidebarExpandedWidth,
        "floor-plan-section-gap": spacing.floorPlanSectionGap,
        "floor-plan-quick-add": spacing.floorPlanQuickAddSize,
        "floor-plan-canvas-dot": spacing.floorPlanCanvasDotSize,
        "floor-plan-grid": spacing.floorPlanCanvasGridSpacing,
        "floor-plan-panel": spacing.floorPlanPanelWidth,
        "floor-plan-panel-padding": spacing.floorPlanPanelPadding,
        "floor-plan-panel-gap": spacing.floorPlanPanelSectionGap,
        "floor-plan-label-margin": spacing.floorPlanLabelMargin,
        "floor-plan-element-gap": spacing.floorPlanElementGap,
        "floor-plan-wall-min": spacing.floorPlanWallMinWidth,
        "floor-plan-wall-h": spacing.floorPlanWallHeight,
        "floor-plan-header": spacing.floorPlanHeaderHeight,
        "floor-plan-icon-btn": spacing.floorPlanIconButtonSize,
        "floor-plan-save-px": spacing.floorPlanSavePaddingX,
        "floor-plan-save-py": spacing.floorPlanSavePaddingY,
        "floor-plan-level-tab-h": spacing.floorPlanLevelTabHeight,
        "floor-plan-level-tab-px": spacing.floorPlanLevelTabPaddingX,
        "floor-plan-add-level-h": spacing.floorPlanAddLevelHeight,
        "floor-plan-section-mb": spacing.floorPlanSectionMarginBottom,
        "floor-plan-quick-add-icon": spacing.floorPlanQuickAddIconSize,
        "floor-plan-pill-h": spacing.floorPlanElementPillHeight,
        "floor-plan-pill-px": spacing.floorPlanElementPillPaddingX,
        "floor-plan-pill-gap": spacing.floorPlanElementPillGap,
        "floor-plan-toolbar": spacing.floorPlanToolbarHeight,
        "floor-plan-status": spacing.floorPlanStatusBarHeight,
        "floor-plan-input-h": spacing.floorPlanFormInputHeight,
        "floor-plan-field-gap": spacing.floorPlanFormFieldGap,
        "floor-plan-delete-h": spacing.floorPlanDeleteButtonHeight,
        "floor-plan-empty-icon": spacing.floorPlanEmptyIconSize,
        "floor-plan-panel-padding-compact": spacing.floorPlanPanelPaddingCompact,
        "floor-plan-header-divider": spacing.floorPlanHeaderDividerMargin,
        "floor-plan-section-label-mb": spacing.floorPlanSectionLabelMb,
        "floor-plan-level-pill-h": spacing.floorPlanLevelPillHeight,
        "floor-plan-level-pill-px": spacing.floorPlanLevelPillPx,
        "floor-plan-level-pill-gap": spacing.floorPlanLevelPillGap,
        "floor-plan-add-level-mt": spacing.floorPlanAddLevelMt,
        "floor-plan-section-divider-m": spacing.floorPlanSectionDividerMargin,
        "floor-plan-table-card-gap": spacing.floorPlanTableCardGap,
        "floor-plan-circle-icon": spacing.floorPlanCircleIconSize,
        "floor-plan-interior-pill-h": spacing.floorPlanInteriorPillHeight,
        "floor-plan-interior-pill-px": spacing.floorPlanInteriorPillPx,
        "floor-plan-interior-pill-gap": spacing.floorPlanInteriorPillGap,
        "floor-plan-walls-placed-mt": spacing.floorPlanWallsPlacedMt,
        "floor-plan-empty-icon-panel": spacing.floorPlanEmptyIconSizePanel,
        "floor-plan-empty-padding": spacing.floorPlanEmptyPadding,
        "floor-plan-selected-padding": spacing.floorPlanSelectedCardPadding,
        "floor-plan-selected-field-gap": spacing.floorPlanSelectedFieldGap,
        "floor-plan-input-h-compact": spacing.floorPlanInputHeightCompact,
        "floor-plan-input-px": spacing.floorPlanInputPx,
        "floor-plan-delete-mt": spacing.floorPlanDeleteMt,
        "floor-plan-delete-h-compact": spacing.floorPlanDeleteHeight,
        "floor-plan-undo-redo-icon": spacing.floorPlanUndoRedoIconSize,
        "floor-plan-save-h": spacing.floorPlanSaveHeight,
      },
      fontSize: {
        xs: fontSizes.xs,
        sm: fontSizes.sm,
        base: fontSizes.base,
        lg: fontSizes.lg,
        xl: fontSizes.xl,
        "2xl": fontSizes["2xl"],
        "3xl": fontSizes["3xl"],
        "4xl": fontSizes["4xl"],
        "5xl": fontSizes["5xl"],
        greeting: fontSizes.greeting,
        "stat-card-label": fontSizes.statCardLabel,
        "stat-card-number": fontSizes.statCardNumber,
        "briefing-label": fontSizes.briefingLabel,
        "guest-name": fontSizes.guestName,
        "guest-detail": fontSizes.guestDetail,
        "floor-plan-header-title": fontSizes.floorPlanHeaderTitle,
        "floor-plan-save": fontSizes.floorPlanSaveFont,
        "floor-plan-level-tab": fontSizes.floorPlanLevelTabFont,
        "floor-plan-add-level": fontSizes.floorPlanAddLevelFont,
        "floor-plan-quick-add-label": fontSizes.floorPlanQuickAddLabel,
        "floor-plan-pill": fontSizes.floorPlanElementPillFont,
        "floor-plan-walls-placed": fontSizes.floorPlanWallsPlacedFont,
        "floor-plan-form": fontSizes.floorPlanFormFont,
        "floor-plan-form-label": fontSizes.floorPlanFormLabel,
        "floor-plan-delete": fontSizes.floorPlanDeleteFont,
        "floor-plan-empty": fontSizes.floorPlanEmptyText,
        "floor-plan-header-title-compact": fontSizes.floorPlanHeaderTitleCompact,
        "floor-plan-save-btn": fontSizes.floorPlanSaveBtn,
        "floor-plan-section-label-size": fontSizes.floorPlanSectionLabelSize,
        "floor-plan-table-card-label": fontSizes.floorPlanTableCardLabel,
        "floor-plan-interior-pill": fontSizes.floorPlanInteriorPillFont,
        "floor-plan-walls-placed-size": fontSizes.floorPlanWallsPlacedFontSize,
        "floor-plan-empty-size": fontSizes.floorPlanEmptyTextSize,
        "floor-plan-field-label-size": fontSizes.floorPlanFieldLabelSize,
        "floor-plan-input-font": fontSizes.floorPlanInputFont,
        "floor-plan-delete-size": fontSizes.floorPlanDeleteFontSize,
      },
      fontWeight: {
        normal: fontWeights.normal,
        medium: fontWeights.medium,
        semibold: fontWeights.semibold,
        bold: fontWeights.bold,
        extrabold: fontWeights.extrabold,
      },
      letterSpacing: {
        "tight-hero": letterSpacing.tightHero,
        "tight-section": letterSpacing.tightSection,
        label: letterSpacing.label,
        "floor-plan-label-tracking": letterSpacing.floorPlanSectionLabelTracking,
      },
      lineHeight: {
        relaxed: lineHeights.relaxed,
      },
      borderRadius: {
        sm: borderRadius.sm,
        md: borderRadius.md,
        lg: borderRadius.lg,
        xl: borderRadius.xl,
        full: borderRadius.full,
        "card-radius-large": borderRadius.cardRadiusLarge,
        "briefing-inner-radius": borderRadius.briefingInnerRadius,
        "button-radius": borderRadius.buttonRadius,
        "floor-plan-pill": borderRadius.floorPlanPillRadius,
        "floor-plan-card": borderRadius.floorPlanCardRadius,
      },
      boxShadow: {
        sm: shadows.sm,
        md: shadows.md,
        lg: shadows.lg,
        soft: shadows.soft,
        "soft-hover": shadows.softHover,
        "gold-glow": colours.goldGlow,
        "gold-glow-stat-card": colours.goldGlowStatCard,
        "stat-card-hover": colours.statCardHoverShadow,
        "gold-glow-hover": colours.goldGlowHover,
        "gold-glow-hero-text": colours.goldGlowHeroText,
        "gold-glow-pricing-card": colours.goldGlowPricingCard,
        "inset-card": colours.insetShadowCard,
      },
      textShadow: {
        "gold-glow-hero": colours.goldGlowHeroText,
      },
      backgroundImage: {
        "gold-gradient-hero": colours.goldGradientHero,
        "gold-gradient-card-top": colours.goldGradientCardTop,
        "gold-gradient-line-top": colours.goldGradientLineTop,
        "gold-gradient-text": colours.goldGradientText,
        "gold-gradient-text-muted": colours.goldGradientTextMuted,
        "gold-glow-section": colours.goldGlowSection,
        "radial-gradient-dark-center": colours.radialGradientDarkCenter,
        "gold-border-gradient": colours.goldBorderGradient,
        "gold-gradient-line-horizontal": colours.goldGradientLineHorizontal,
        "header-divider-gradient": colours.headerDividerGradient,
        "grid-pattern": `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100' height='100'%3E%3Cdefs%3E%3Cpattern id='d' width='24' height='24' patternUnits='userSpaceOnUse'%3E%3Ccircle cx='12' cy='12' r='0.5' fill='white'/%3E%3C/pattern%3E%3C/defs%3E%3Crect width='100' height='100' fill='url(%23d)'/%3E%3C/svg%3E")`,
        "floor-plan-dot-grid": `radial-gradient(circle, ${colours.floorPlanCanvasDot} 2px, transparent 0)`,
        "floor-plan-canvas-container-dot-grid": colours.floorPlanCanvasContainerDotGrid,
      },
      backgroundSize: {
        "floor-plan-grid": `${spacing.floorPlanCanvasGridSpacing} ${spacing.floorPlanCanvasGridSpacing}`,
      },
      backgroundColor: {
        "floor-plan-panel-bg": colours.floorPlanPanelBg,
        "floor-plan-card-bg": colours.floorPlanCardBg,
        "floor-plan-card-hover-bg": colours.floorPlanCardHoverBg,
        "floor-plan-selected-card-bg": colours.floorPlanSelectedCardBg,
        "floor-plan-input-bg": colours.floorPlanInputBg,
        "floor-plan-delete-bg": colours.floorPlanDeleteBg,
        "floor-plan-delete-hover-bg": colours.floorPlanDeleteHoverBg,
        "floor-plan-canvas": colours.floorPlanCanvasBg,
        "floor-plan-canvas-container": colours.floorPlanCanvasContainerBg,
        "gold-tint": colours.goldTintBg,
        "surface-glass": colours.surfaceGlass,
        "surface-glass-soft": colours.surfaceGlassSoft,
        "gold-glass": colours.goldGlass,
        "stat-card-glass": colours.statCardGlass,
        "top-nav-glass": colours.topNavGlass,
        "content-inner": colours.contentInnerBg,
        "content-inner-muted": colours.contentInnerBgMuted,
        "auth-card": colours.authCardBg,
        "auth-input": colours.authInputBg,
        "stat-card-bg": colours.statCardBg,
        "card-bg": colours.cardBg,
        "briefing-inner-bg": colours.briefingInnerBg,
        "top-nav-bg": colours.topNavBg,
        "sidebar-bg": colours.sidebarBg,
        "row-hover-bg": colours.rowHoverBg,
      },
      borderColor: {
        "floor-plan-panel-border": colours.floorPlanPanelBorder,
        "floor-plan-section-divider": colours.floorPlanSectionDivider,
        "floor-plan-card-border": colours.floorPlanCardBorder,
        "floor-plan-card-hover-border": colours.floorPlanCardHoverBorder,
        "floor-plan-circle-border": colours.floorPlanCircleBorder,
        "floor-plan-inactive-border": colours.floorPlanInactiveBorder,
        "floor-plan-inactive-hover-border": colours.floorPlanInactiveHoverBorder,
        "floor-plan-pill-border": colours.floorPlanPillBorder,
        "floor-plan-pill-hover-border": colours.floorPlanPillHoverBorder,
        "floor-plan-wall-pill-border": colours.floorPlanWallPillBorder,
        "floor-plan-selected-card-border": colours.floorPlanSelectedCardBorder,
        "floor-plan-input-border": colours.floorPlanInputBorder,
        "floor-plan-delete-border": colours.floorPlanDeleteBorder,
        "gold-glass": colours.goldGlassBorder,
        "stat-card-glass": colours.statCardGlassBorder,
        "top-nav-border": colours.topNavBorder,
        "content-inner": colours.contentInnerBorder,
        "border-subtle": colours.borderSubtle,
        "auth-card": colours.authCardBorder,
        "auth-input": colours.authInputBorder,
        "stat-card-border": colours.statCardBorder,
        "stat-card-gold-top": colours.statCardGoldTop,
        "stat-card-hover-border": colours.statCardHoverBorder,
        "card-border": colours.cardBorder,
        "row-divider": colours.rowDivider,
        "sidebar-border": colours.sidebarBorder,
        "top-nav-border-bottom": colours.topNavBorderBottom,
        "briefing-inner-border": colours.briefingInnerBorder,
      },
      ringColor: {
        "auth-focus": colours.authFocusRing,
      },
      keyframes: {
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "200% 0" },
          "100%": { backgroundPosition: "-200% 0" },
        },
        gradientBorder: {
          "0%, 100%": { opacity: "0.5" },
          "50%": { opacity: "1" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        waveform: {
          "0%, 100%": { transform: "scaleY(0.3)" },
          "50%": { transform: "scaleY(1)" },
        },
      },
      animation: {
        "fade-in-up": "fadeInUp 0.6s ease-out forwards",
        shimmer: "shimmer 2s ease-in-out",
        "gradient-border": "gradientBorder 2s ease-in-out infinite",
        pulse: "pulse 2s ease-in-out infinite",
        waveform: "waveform 1.2s ease-in-out infinite",
      },
      transitionDuration: {
        "200": "200ms",
        "400": "400ms",
        "600": "600ms",
      },
      backdropBlur: {
        "stat-card": "24px",
        "app-nav": "20px",
      },
      backdropSaturate: {
        "stat-card": "2",
        "app-card": "1.8",
      },
    },
  },
  plugins: [],
};

export default config;
