import type { NavItem } from "@seatly/types";

export const NAV_ITEMS: NavItem[] = [
  { href: "/floor-plan", label: "Floor Plan", roles: ["host", "owner", "admin"] },
  { href: "/reservations", label: "Reservations", roles: ["host", "owner", "admin"] },
  { href: "/reservations/new", label: "New Reservation", roles: ["host", "owner", "admin"] },
  { href: "/waitlist", label: "Waitlist", roles: ["host", "owner"] },
  { href: "/guests/search", label: "Guest Search", roles: ["host", "waiter", "owner", "admin"] },
  { href: "/my-tables", label: "My Tables", roles: ["waiter"] },
  { href: "/kitchen", label: "Kitchen Display", roles: ["kitchen"] },
  { href: "/dashboard", label: "Dashboard", roles: ["owner", "admin"] },
  { href: "/crm", label: "CRM", roles: ["owner", "admin"] },
  { href: "/analytics", label: "Analytics", roles: ["owner", "admin"] },
  { href: "/analytics/menu", label: "Menu Analytics", roles: ["owner", "admin"] },
  { href: "/menu", label: "Menu", roles: ["owner", "admin"] },
  { href: "/settings", label: "Settings", roles: ["owner", "admin"] },
  { href: "/settings/floor-plan", label: "Floor Plan Editor", roles: ["owner", "admin"] },
  { href: "/settings/shifts", label: "Shifts", roles: ["owner", "admin"] },
  { href: "/settings/staff", label: "Staff", roles: ["owner", "admin"] },
  { href: "/staff/schedule", label: "Schedule", roles: ["owner", "admin"] },
  { href: "/events", label: "Events", roles: ["owner", "admin"] },
  { href: "/marketing", label: "Marketing", roles: ["owner", "admin"] },
  { href: "/assistant", label: "AI Assistant", roles: ["owner", "admin"] },
  { href: "/billing", label: "Billing", roles: ["owner", "admin"] },
  { href: "/onboarding", label: "Onboarding", roles: ["owner"] },
  { href: "/admin", label: "Admin", roles: ["admin"] },
];
