import { z } from "zod";
import { BoundedText, NonEmptyText, Uuid } from "./base.ts";

// Invite tokens are random opaque strings generated by the DB. Bound length;
// keep the character class permissive so we don't accidentally reject a
// future token format.
const InviteToken = z
  .string()
  .trim()
  .min(8)
  .max(200)
  .regex(/^[A-Za-z0-9._\-]+$/, "Invalid invite token format");

export const AcceptHostInviteSchema = z.object({
  token: InviteToken,
});

export type AcceptHostInviteInput = z.infer<typeof AcceptHostInviteSchema>;

export const AcceptStaffInviteSchema = z.object({
  token: InviteToken,
  action: z.enum(["accept", "decline", "preview"]).optional(),
});

export type AcceptStaffInviteInput = z.infer<typeof AcceptStaffInviteSchema>;

export const ApproveStaffActionSchema = z.object({
  restaurant_id: Uuid,
  // Free-form action string identifying which staff action is being approved
  // (e.g. "reservation.discount", "order.void"). Bound length.
  action: NonEmptyText(80),
  manager_email: z.string().trim().toLowerCase().email().max(254),
  // Passwords are not bound at the upper end because Supabase Auth accepts
  // long passphrases; we just require non-empty.
  manager_password: z.string().min(1).max(256),
});

export type ApproveStaffActionInput = z.infer<typeof ApproveStaffActionSchema>;

// invite-host / invite-staff share the same "create | cancel" action shape,
// with invite-staff adding role + permission_overrides_json.
const PermissionKey = z.enum([
  "overview",
  "reservations",
  "floorPlan",
  "staffInvites",
  "orders",
  "menu",
  "crm",
  "analytics",
  "expenses",
  "events",
  "promotions",
  "export",
  "restaurant",
  "settings",
]);

const PermissionOverridesSchema = z
  .object({
    allow: z.array(PermissionKey).max(20).optional(),
    deny: z.array(PermissionKey).max(20).optional(),
  })
  .strict();

export const InviteHostSchema = z.object({
  action: z.enum(["create", "cancel", "resend"]).optional(),
  restaurant_id: Uuid.optional(),
  restaurantId: Uuid.optional(),
  invite_id: Uuid.optional(),
  inviteId: Uuid.optional(),
  // contact is normalized inside the fn (email vs phone branch); accept
  // either shape and let the existing normalizers run on the trimmed string.
  contact: BoundedText(254).optional(),
});

export type InviteHostInput = z.infer<typeof InviteHostSchema>;

export const InviteStaffSchema = z.object({
  action: z.enum(["create", "cancel", "resend"]).optional(),
  restaurant_id: Uuid.optional(),
  restaurantId: Uuid.optional(),
  invite_id: Uuid.optional(),
  inviteId: Uuid.optional(),
  contact: BoundedText(254).optional(),
  role: z.enum(["owner", "manager", "host"]).optional(),
  permission_overrides_json: PermissionOverridesSchema.optional(),
  // Mobile / legacy clients sometimes use camelCase.
  permissionOverrides: PermissionOverridesSchema.optional(),
});

export type InviteStaffInput = z.infer<typeof InviteStaffSchema>;
